#+TITLE: Snickerdoodle AXI notes

* References:

** FPGA Developer

The FPGA Developer tutorials start with this base system, based on the MicroZed board.
http://www.fpgadeveloper.com/2014/07/creating-a-base-system-for-the-zynq-in-vivado.html

Then proceed to this axi loopback tutorial.
http://www.fpgadeveloper.com/2014/08/using-the-axi-dma-in-vivado.html

A previous version of the lookback tutorial using EDK instead of Vivado is here:
http://www.fpgadeveloper.com/2014/03/using-the-axi-dma-engine.html 
and it relied upon the Base System Builder
http://www.fpgadeveloper.com/2014/02/creating-a-project-using-the-base-system-builder-2.html

* Set up

Using a snickerdoodle black v4.1 with Vivado 2018.2

* create the base system using vivado

Even through the tutorial was based on the microzed board, it worked fine with the snickerdoodle black board using the basic hardware setup developed in [[file:blink.org]].

With the snickerdoodle board, programming the FPGA using the Diligent JTAG cable causes the white led heartbeat light to start up. Then connect via screen
#+begin_src
screen /dev/ttyACM0 115200
#+end_src
and every time the "Run->Run As->Run on hardware" is selected in the SDK, the board will respond with "Hello World"

* create AXI DMA

This relies on the base system developed earlier. 

Worked through this demo up to the SDK portion. there are a series of problems related to finding the correct header files for compilation.
